// 业务类型
// 文档
export const ENTITY_TYPE_DOCUMENT = 'DOCUMENT'

// 文档权限项
export const DOCUMENT_PERMISSION_ITEM = 'DocumentPermissionItem'

// 文件夹按组织机构授权模式
export const FOLDER_GRANT_PERMISSION_MODE_ORGANIZATION = 'ORGANIZATION'

// 文件夹按用户组授权模式
export const FOLDER_GRANT_PERMISSION_MODE_USER_GROUP = 'USER_GROUP'

// 文档权限编码
export const CREATE_FOLDER = 'CREATE_FOLDER'
export const REMOVE_FOLDER = 'REMOVE_FOLDER'
export const RENAME_FOLDER = 'RENAME_FOLDER'
export const COPY_FOLDER = 'COPY_FOLDER'
export const MOVE_FOLDER = 'MOVE_FOLDER'
export const GRANT_PERMISSION_BY_USER_GROUP = 'GRANT_PERMISSION_BY_USER_GROUP'
export const GRANT_PERMISSION_BY_ORGANIZATION = 'GRANT_PERMISSION_BY_ORGANIZATION'
export const PREVIEW_DOCUMENT = 'PREVIEW_DOCUMENT'
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT'
export const DOWNLOAD_DOCUMENT = 'DOWNLOAD_DOCUMENT'
export const RENAME_DOCUMENT = 'RENAME_DOCUMENT'
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'
export const COPY_DOCUMENT = 'COPY_DOCUMENT'
export const MOVE_DOCUMENT = 'MOVE_DOCUMENT'
export const LOCK_DOCUMENT = 'LOCK_DOCUMENT'
export const UNLOCK_DOCUMENT = 'UNLOCK_DOCUMENT'
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT'
export const VIEW_DOCUMENT_VERSION = 'VIEW_DOCUMENT_VERSION'
export const RESTORE_DOCUMENT_VERSION = 'RESTORE_DOCUMENT_VERSION'
export const SHARE_DOCUMENT = 'SHARE_DOCUMENT'
export const NO_MENU_AVAILABLE = 'NO_MENU_AVAILABLE'

// 文件夹
export const POP_DOCUMENT_TYPE_FOLDER = 'FOLDER'

// 文档
export const POP_DOCUMENT_TYPE_DOCUMENT = 'DOCUMENT'
